### ISSUE TITLE
Expose Fragment constructor with layoutId.

### ISSUE THREAD

**Issue by evant** [taekwonjoe01/BetterJetpackNav#21]
Fragments have a constructor that [can take a layoutId](https://developer.android.com/reference/androidx/fragment/app/Fragment?hl=en#Fragment(int)) so that you don't have to override onCreateView. Can this lib's fragments sub-classes expose that constructor?

**Comment by taekwonjoe01** [comment]
@evant 
Seems like a reasonable request. I just made the changes, so try it out:
If you were using `2.0.0`, grab `2.0.1-rc01`
If you were using the `3.0.0-rcxx`, grab `3.0.0-rc03`

Let me know if that works.

**Comment by evant** [comment]
Yep, works great!
